# Generated by Django 4.2.1 on 2023-06-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchariapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', models.ImageField(upload_to='pics')),
                ('nam', models.CharField(max_length=250)),
                ('descrip', models.TextField()),
            ],
        ),
    ]
